version: '3'
services:
  server:
    image: golang:1.12.5
    depends_on:
      - nats
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
      - go-cache:/root/.cache/go-build
    working_dir: /app
    command: go run cmd/main.go server start
    environment:
      NATS_CLUSTER_ID: test-cluster
      NATS_URL: nats://nats:4222
      NATS_CLIENT_ID: server
      BIND_ADDRESS: 0.0.0.0:50051
    ports:
      - "50051:50051"

  proxy:
    image: jjbubudi/grpc-web-proxy:v0.9.5
    command: --allow_all_origins --backend_addr=server:50051 --run_tls_server=false --backend_tls=false
    ports:
      - "50052:8080"

  nats:
    image: nats-streaming:0.16.2
    command: -store file -dir /data
    ports:
      - "4222:4222"
    volumes:
      - nats-data:/data

volumes:
  nats-data:
  go-mod-cache:
  go-cache: